# Generated by Django 5.0.4 on 2024-08-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Подтвержденный"),
        ),
    ]
